"""empty message

Revision ID: 26549f8b42ec
Revises: b4198aaa185c
Create Date: 2025-11-03 21:34:34.198540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26549f8b42ec'
down_revision = 'b4198aaa185c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('is_complete')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_complete', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
